/**
 * Seed data for Smell Bess, generated by hand from `scent-lists.md`
 * (Bess List, locked 5 Oct 2026) and `CLAUDE.md`.
 *
 * - 9 scents are `live`: the 7-scent launch buy (revised 5 Oct 2026: two
 *   bottles each, one kept sealed and sold whole at `bottle.price`) plus
 *   Amber Oud Gold and Marwa from the owner's shelf (decants only). Arabians
 *   only at launch. The rest of the Bess List is `coming_soon` until bought;
 *   Rayhaan Elixir was dropped and is `retired`.
 * - Note lists come from Fragrantica (our main source for scent facts; the
 *   page id is above each list). Every rating, take, blurb and "smells like" line here is our
 *   DRAFT (`draft: true`). Claude drafts it; the owners edit it before launch.
 *   Empty `smellsLike` means "owner to fill in". The set copy is the owner's.
 * - Decant prices are NOT here: they come from the tier (src/lib/pricing.ts).
 *   Sealed-bottle prices are per product (`bottle`), matched to the local
 *   market (business-plan.md §2.4a); four are still to confirm.
 * - Bank details are NOT on the site at all.
 */
import type { Area, Bottle, CuratedSet, Product, Settings } from "@/lib/types";

const none = { top: [], heart: [], base: [] };

export const PRODUCTS: Product[] = [
  // ------------------- launch: 7 bought (2 bottles each, 1 sealed) + 2 from the owner's shelf
  {
    id: "liquid-brun",
    house: "French Avenue",
    name: "Liquid Brun",
    variant: "Original EDP",
    tier: "A",
    gender: "him",
    status: "live",
    smellsLike: ["Parfums de Marly Althaïr DNA"],
    // Fragrantica #94713
    notes: {
      top: ["cinnamon", "orange blossom", "cardamom", "bergamot"],
      heart: ["bourbon vanilla", "elemi"],
      base: ["praline", "ambroxan", "musk", "guaiac wood"],
    },
    vibes: ["sweet", "gourmand", "spicy"],
    occasions: ["date", "lime"],
    ratings: { heat: 3, longevity: 4, projection: 4, compliments: 5 },
    take: { by: "him", text: "Warm vanilla and spice that gets noticed. Best after dark." },
    blurb: "Boozy vanilla with a cinnamon kick. A night-time compliment getter.",
    draft: true,
    hue: 28,
    wear: { time: "night", weather: "cold" },
    image: "/scents/liquid-brun.webp",
    bottle: { sizeMl: 100, price: 499 },
  },
  {
    id: "hawas-ice",
    house: "Rasasi",
    name: "Hawas Ice",
    tier: "A",
    gender: "him",
    status: "live",
    smellsLike: [],
    inspiredBy: ["Paco Rabanne Invictus Aqua"],
    // Fragrantica #89050
    notes: {
      top: ["apple", "lemon", "bergamot", "star anise"],
      heart: ["plum", "orange blossom", "cardamom"],
      base: ["musk", "amber", "driftwood", "moss"],
    },
    vibes: ["fresh", "aquatic", "fruity"],
    occasions: ["fete", "lime", "office"],
    ratings: { heat: 5, longevity: 4, projection: 4, compliments: 4 },
    take: { by: "him", text: "Cold, sweet and fresh. Made for a hot day in a crowd." },
    blurb: "An icy take on the Hawas DNA. A fete weapon.",
    draft: true,
    hue: 195,
    wear: { time: "day", weather: "warm" },
    image: "/scents/hawas-ice.webp",
    bottle: { sizeMl: 100, price: 499 },
  },
  {
    id: "hawas-diva",
    house: "Rasasi",
    name: "Hawas Diva",
    tier: "A",
    gender: "her",
    status: "live",
    smellsLike: [],
    inspiredBy: ["Valentino Born in Roma Intense"],
    // Fragrantica #113190
    notes: {
      top: ["red fruits", "rhubarb", "lychee"],
      heart: ["rose", "frankincense", "cedar"],
      base: ["vanilla", "musk", "ambergris"],
    },
    vibes: ["fruity", "floral", "sweet"],
    occasions: ["lime", "date", "fete"],
    ratings: { heat: 4, longevity: 4, projection: 4, compliments: 4 },
    take: { by: "her", text: "Fruity, girly and loud enough to be noticed." },
    blurb: "Bright fruity floral from the Hawas line.",
    draft: true,
    hue: 330,
    wear: { time: "any", weather: "warm" },
    image: "/scents/hawas-diva.webp",
    bottle: { sizeMl: 100, price: 450 },
  },
  {
    id: "angham",
    house: "Lattafa",
    name: "Angham",
    tier: "A",
    gender: "unisex",
    leans: "her",
    status: "live",
    smellsLike: ["Burberry Goddess"],
    // Fragrantica #96768
    notes: {
      top: ["ginger", "mandarin", "pink pepper"],
      heart: ["lavender", "praline", "cacao", "jasmine"],
      base: ["vanilla", "amber", "musk"],
    },
    vibes: ["sweet", "floral"],
    occasions: ["date", "office"],
    ratings: { heat: 3, longevity: 4, projection: 3, compliments: 4 },
    take: { by: "her", text: "Soft and pretty. Leans feminine, but anyone can wear it." },
    blurb: "A smooth unisex scent that leans feminine.",
    draft: true,
    hue: 300,
    wear: { time: "any", weather: "any" },
    image: "/scents/angham.webp",
    bottle: { sizeMl: 100, price: 475 },
  },
  {
    id: "khamrah",
    house: "Lattafa",
    name: "Khamrah",
    tier: "A",
    gender: "unisex",
    status: "coming_soon",
    smellsLike: ["Kilian Angels' Share"],
    // Fragrantica #75805
    notes: {
      top: ["cinnamon", "nutmeg", "bergamot"],
      heart: ["dates", "praline", "tuberose", "mahonial"],
      base: ["vanilla", "tonka bean", "amberwood", "myrrh", "benzoin", "akigalawood"],
    },
    vibes: ["sweet", "gourmand", "spicy", "amber"],
    occasions: ["date", "lime"],
    ratings: { heat: 3, longevity: 5, projection: 4, compliments: 5 },
    take: { by: "him", text: "The global best seller for a reason. Two sprays is plenty." },
    blurb: "Dates, cinnamon and vanilla. Rich, sweet and long-lasting.",
    draft: true,
    hue: 18,
  },
  {
    id: "khamrah-qahwa",
    house: "Lattafa",
    name: "Khamrah Qahwa",
    tier: "A",
    gender: "unisex",
    status: "coming_soon",
    smellsLike: [],
    inspiredBy: ["Kilian Angels' Share"],
    // Fragrantica #88175
    notes: {
      top: ["cinnamon", "cardamom", "ginger"],
      heart: ["praline", "candied fruits", "white flowers"],
      base: ["vanilla", "coffee", "tonka bean", "benzoin", "musk"],
    },
    vibes: ["gourmand", "coffee", "spicy", "sweet"],
    occasions: ["date", "office"],
    ratings: { heat: 3, longevity: 5, projection: 4, compliments: 4 },
    take: { by: "him", text: "Khamrah with a coffee twist. A bit drier and easier for the office." },
    blurb: "Khamrah's sweet spice with roasted coffee on top.",
    draft: true,
    hue: 30,
  },
  {
    id: "yara",
    house: "Lattafa",
    name: "Yara",
    variant: "Original (pink)",
    tier: "A",
    gender: "her",
    status: "coming_soon",
    smellsLike: ["Valentino Born in Roma Donna"],
    // Fragrantica #76880
    notes: {
      top: ["orchid", "heliotrope", "tangerine"],
      heart: ["gourmand accord", "tropical fruits"],
      base: ["vanilla", "musk", "sandalwood"],
    },
    vibes: ["sweet", "gourmand", "fruity"],
    occasions: ["lime", "date", "office"],
    ratings: { heat: 3, longevity: 4, projection: 3, compliments: 5 },
    take: { by: "her", text: "Creamy, sweet and soft. The one people ask about." },
    blurb: "Creamy pink gourmand. Sweet without being sickly.",
    draft: true,
    hue: 340,
  },
  {
    id: "rayhaan-aquatica",
    house: "Rayhaan",
    name: "Aquatica",
    tier: "A",
    gender: "him",
    leans: "him",
    status: "live",
    smellsLike: ["Creed Virgin Island Water"],
    // Fragrantica #120605
    notes: {
      top: ["lime", "coconut milk", "bergamot", "mandarin"],
      heart: ["sugar cane", "jasmine", "hibiscus", "gardenia"],
      base: ["musk", "rum", "tonka bean", "patchouli"],
    },
    vibes: ["fresh", "aquatic"],
    occasions: ["office", "lime", "fete"],
    ratings: { heat: 5, longevity: 3, projection: 3, compliments: 3 },
    take: { by: "him", text: "Clean and fresh. Spray it and go to work in the heat." },
    blurb: "Fresh aquatic that's built for TT heat. Men's, works unisex.",
    draft: true,
    hue: 185,
    wear: { time: "day", weather: "warm" },
    image: "/scents/rayhaan-aquatica.webp",
    bottle: { sizeMl: 100, price: 450 },
  },
  {
    id: "rayhaan-elixir",
    house: "Rayhaan",
    name: "Elixir",
    tier: "A",
    gender: "unisex",
    status: "retired",
    smellsLike: [],
    notes: none,
    vibes: ["sweet", "amber"],
    occasions: ["date", "fete", "lime"],
    ratings: { heat: 4, longevity: 4, projection: 4, compliments: 4 },
    take: { by: "him", text: "Sold out everywhere else for a reason." },
    blurb: "A unisex crowd-pleaser.",
    draft: true,
    hue: 45,
  },
  {
    id: "supremacy-collectors-edition",
    house: "Afnan",
    name: "Supremacy Collector's Edition",
    tier: "A+",
    gender: "him",
    status: "coming_soon",
    smellsLike: [],
    inspiredBy: ["Creed Aventus Absolu"],
    // Fragrantica #98689
    notes: {
      top: ["pineapple", "bergamot", "white flowers", "apple"],
      heart: ["orange blossom", "birch", "amber"],
      base: ["oakmoss", "musk", "ambergris"],
    },
    vibes: ["fruity", "woody", "fresh"],
    occasions: ["office", "date", "lime"],
    ratings: { heat: 4, longevity: 4, projection: 4, compliments: 4 },
    take: { by: "him", text: "The premium pick. Only Smell Bess carries it locally." },
    blurb: "Premium Arabian. Polished, confident and versatile.",
    draft: true,
    hue: 220,
  },
  {
    id: "asad-bourbon",
    house: "Lattafa",
    name: "Asad Bourbon",
    tier: "A",
    gender: "him",
    status: "coming_soon",
    smellsLike: [],
    inspiredBy: ["Azzaro Most Wanted"],
    // Fragrantica #101124
    notes: {
      top: ["lavender", "mirabelle", "pink pepper"],
      heart: ["cacao", "nutmeg", "davana"],
      base: ["bourbon vanilla", "amber", "vetiver"],
    },
    vibes: ["spicy", "amber", "sweet"],
    occasions: ["date", "lime"],
    ratings: { heat: 3, longevity: 4, projection: 4, compliments: 4 },
    take: { by: "him", text: "Warm, boozy and spicy. A night-out scent." },
    blurb: "The new Asad: warmer and boozier than the original.",
    draft: true,
    hue: 20,
  },
  {
    id: "pride-nebras",
    house: "Lattafa",
    name: "Pride Nebras",
    tier: "A",
    gender: "unisex",
    status: "live",
    smellsLike: ["Billie Eilish Eilish"],
    // Fragrantica #78560
    notes: {
      top: ["red berries", "mandarin"],
      heart: ["vanilla", "cacao", "rose"],
      base: ["sugar", "tonka bean", "musk", "amber"],
    },
    vibes: ["sweet", "gourmand"],
    occasions: ["date", "lime"],
    ratings: { heat: 3, longevity: 4, projection: 4, compliments: 4 },
    take: { by: "her", text: "Sweet and cosy. Anyone can wear it." },
    blurb: "A sweet, wearable gourmand from Lattafa's Pride line.",
    draft: true,
    hue: 15,
    wear: { time: "night", weather: "cold" },
    image: "/scents/pride-nebras.webp",
    bottle: { sizeMl: 100, price: 425 },
  },
  {
    id: "musamam-black-intense",
    house: "Lattafa",
    name: "Musamam Black Intense",
    tier: "A+",
    gender: "him",
    status: "live",
    smellsLike: [],
    // Fragrantica #119987
    notes: {
      top: ["lavender", "nutmeg", "sage", "bergamot"],
      heart: ["cedarwood", "geranium", "mahonial", "rosyfolia"],
      base: ["cocoa", "tonka bean", "maple", "ambrofix", "patchouli"],
    },
    vibes: ["sweet", "amber", "woody"],
    occasions: ["date", "lime"],
    ratings: { heat: 3, longevity: 5, projection: 4, compliments: 4 },
    take: { by: "him", text: "Dark and rich. Sold out at the other shop in every size." },
    blurb: "An original by perfumer Jordi Fernández. Lavender and nutmeg open into creamy cocoa, tonka and maple. Dark, smooth and addictive. People lean in to ask what you have on.",
    draft: true,
    hue: 270,
    wear: { time: "night", weather: "cold" },
    image: "/scents/musamam-black-intense.webp",
    bottle: { sizeMl: 100, price: 599 },
  },
  {
    id: "amber-oud-gold",
    house: "Al Haramain",
    name: "Amber Oud Gold Edition",
    tier: "A+",
    gender: "unisex",
    status: "live",
    smellsLike: [],
    inspiredBy: ["Xerjoff Erba Pura"],
    // Fragrantica #51816
    notes: {
      top: ["bergamot", "green notes"],
      heart: ["melon", "pineapple", "amber", "gourmand accord"],
      base: ["vanilla", "musk", "woody notes"],
    },
    vibes: ["sweet", "amber", "fruity"],
    occasions: ["fete", "lime"],
    ratings: { heat: 4, longevity: 5, projection: 5, compliments: 5 },
    take: { by: "him", text: "Loud, sweet and golden. People will ask what you're wearing." },
    blurb: "Sweet amber with juicy melon and pineapple over vanilla. Fills a room.",
    draft: true,
    hue: 48,
    wear: { time: "any", weather: "cold" },
    image: "/scents/amber-oud-gold.webp",
  },
  {
    id: "marwa",
    house: "Arabiyat Prestige",
    name: "Marwa",
    tier: "A",
    gender: "him",
    status: "live",
    smellsLike: ["Louis Vuitton Imagination"],
    // Fragrantica #107084
    notes: {
      top: ["bergamot", "lemon", "orange"],
      heart: ["ginger", "neroli", "cinnamon"],
      base: ["black tea", "ambroxan", "olibanum", "guaiac wood"],
    },
    vibes: ["fresh", "fruity"],
    occasions: ["office", "lime"],
    ratings: { heat: 4, longevity: 4, projection: 3, compliments: 4 },
    take: { by: "him", text: "Fresh and fruity. Sells out at the other shops." },
    blurb: "Bright citrus, ginger and cinnamon over black tea. Clean, classy and easy to wear.",
    draft: true,
    hue: 160,
    wear: { time: "day", weather: "warm" },
    image: "/scents/marwa.webp",
  },

  // ---------------------------------------------------------- coming soon (9 more)
  {
    ...comingSoon("rare-reef", "Afnan", "Rare Reef", "A", "unisex", ["fresh", "fruity"], 170, {
      // Fragrantica #106835
      top: ["orange", "mint", "citron", "grapefruit", "blackcurrant", "coriander"],
      heart: ["apricot", "basil", "violet leaf", "rose"],
      base: ["fig", "ambrette", "amberwood", "dates"],
    }),
    inspiredBy: ["Louis Vuitton Pacific Chill"],
  },
  comingSoon("cdn-untold", "Armaf", "Club de Nuit Untold", "A", "unisex", ["sweet", "amber", "woody"], 350),
  comingSoon("teriaq-intense", "Lattafa", "Teriaq Intense", "A", "unisex", ["sweet", "gourmand", "amber"], 10),
  comingSoon("vintage-radio", "Lattafa", "Vintage Radio", "A", "unisex", ["woody", "sweet"], 40),
  comingSoon("9pm-night-out", "Afnan", "9PM Night Out", "A+", "him", ["sweet", "spicy"], 265),
  comingSoon("yara-elixir", "Lattafa", "Yara Elixir", "A+", "her", ["sweet", "fruity"], 320),
  comingSoon("atheeri", "Lattafa", "Atheeri", "A+", "her", ["floral", "sweet"], 280),
  comingSoon("gos-full-house", "Jo Milano", "Game of Spades Full House", "N", "unisex", ["sweet", "woody"], 0),
  comingSoon("gos-wildcard", "Jo Milano", "Game of Spades Wildcard", "N", "unisex", ["floral", "woody"], 260),
];

function comingSoon(
  id: string,
  house: string,
  name: string,
  tier: Product["tier"],
  gender: Product["gender"],
  vibes: Product["vibes"],
  hue: number,
  notes: Product["notes"] = none,
): Product {
  return {
    id,
    house,
    name,
    tier,
    gender,
    status: "coming_soon",
    smellsLike: [],
    notes,
    vibes,
    occasions: [],
    blurb: "Approved for the Bess List. On the way in a future drop.",
    draft: true,
    hue,
  };
}

/**
 * Curated sets: the owner's launch names and copy (business-plan.md §2.3b).
 * The scents were re-mapped on 5 Oct 2026 when the launch cart changed; the
 * swaps are DRAFTS for the owners to confirm by smell. Tier A only, except
 * the Fete Pack and Date Night, which each have an A+ scent and their own price.
 */
export const SETS: CuratedSet[] = [
  {
    id: "fete-pack",
    name: "Fete Pack",
    description:
      "If you want to be the star of the show, turn heads when you pass, and get stopped randomly, this selection here is for you.",
    productIds: ["hawas-ice", "rayhaan-aquatica", "amber-oud-gold"],
    price: { 5: 175, 10: 300 },
    draft: false,
  },
  {
    id: "for-her",
    name: "For Her",
    description:
      "These are some of the best smelling scents around. Guaranteed she will love AT LEAST one.",
    productIds: ["hawas-diva", "angham", "pride-nebras"],
    draft: false,
  },
  {
    id: "date-night",
    name: "Date Night",
    description:
      "Warning! Now listen fellas, ladies will want to be all up in your space with this pack here. You will smell better than the dessert menu.",
    productIds: ["liquid-brun", "pride-nebras", "musamam-black-intense"],
    price: { 5: 175, 10: 300 },
    draft: false,
  },
  {
    id: "office-school-days",
    name: "Office/School Days",
    description:
      "Smell the bess at the office or school, make a statement without saying a word. Go light on sprays: 2–4 max.",
    productIds: ["rayhaan-aquatica", "hawas-ice", "marwa"],
    draft: false,
  },
];

/**
 * DEMO stock so the shop can be clicked through locally. The launch bottles
 * haven't arrived yet (Jomashop order on or after 17 Oct 2026). Replace with
 * real bottle IDs and ml once they're in hand. Costs are landed TT$ from
 * scent-lists.md.
 */
const DEMO_ONLY: Bottle[] = [
  // Open bottles (decant stock). One is low so the low-stock badge shows.
  { id: "LB-01", productId: "liquid-brun", sizeMl: 100, mlRemaining: 95, costTtd: 355, source: "Jomashop" },
  { id: "HI-01", productId: "hawas-ice", sizeMl: 100, mlRemaining: 22, costTtd: 295, source: "Jomashop" },
  { id: "HD-01", productId: "hawas-diva", sizeMl: 100, mlRemaining: 95, costTtd: 414, source: "Jomashop" },
  { id: "AN-01", productId: "angham", sizeMl: 100, mlRemaining: 95, costTtd: 390, source: "Jomashop" },
  { id: "PN-01", productId: "pride-nebras", sizeMl: 100, mlRemaining: 95, costTtd: 296, source: "Jomashop" },
  { id: "MB-01", productId: "musamam-black-intense", sizeMl: 100, mlRemaining: 95, costTtd: 532, source: "Jomashop" },
  { id: "RA-01", productId: "rayhaan-aquatica", sizeMl: 100, mlRemaining: 95, costTtd: 300, source: "Local Rayhaan dealer" },
  // Sealed bottles, sold whole. Hawas Diva's has already sold, to show decants-only.
  { id: "LB-S1", productId: "liquid-brun", sizeMl: 100, mlRemaining: 100, costTtd: 355, source: "Jomashop", sealed: true },
  { id: "HI-S1", productId: "hawas-ice", sizeMl: 100, mlRemaining: 100, costTtd: 295, source: "Jomashop", sealed: true },
  { id: "HD-S1", productId: "hawas-diva", sizeMl: 100, mlRemaining: 100, costTtd: 414, source: "Jomashop", sealed: true, soldAt: "2026-11-07T14:00:00.000Z" },
  { id: "AN-S1", productId: "angham", sizeMl: 100, mlRemaining: 100, costTtd: 390, source: "Jomashop", sealed: true },
  { id: "PN-S1", productId: "pride-nebras", sizeMl: 100, mlRemaining: 100, costTtd: 296, source: "Jomashop", sealed: true },
  { id: "MB-S1", productId: "musamam-black-intense", sizeMl: 100, mlRemaining: 100, costTtd: 532, source: "Jomashop", sealed: true },
  { id: "RA-S1", productId: "rayhaan-aquatica", sizeMl: 100, mlRemaining: 100, costTtd: 300, source: "Local Rayhaan dealer", sealed: true },
];

/**
 * REAL bottles from the owner's shelf (ml as of 5 Oct 2026). Cost is
 * replacement cost. These are the only bottles seeded into Supabase; the
 * launch bottles are added in admin when they arrive.
 */
export const OWNER_SHELF_BOTTLES: Bottle[] = [
  { id: "AG-01", productId: "amber-oud-gold", sizeMl: 120, mlRemaining: 50, costTtd: 550, source: "Owner's shelf" },
  { id: "MW-01", productId: "marwa", sizeMl: 100, mlRemaining: 80, costTtd: 441, source: "Owner's shelf" },
];

/** Local JSON store only: demo stock for every launch scent + the real shelf bottles. */
export const DEMO_BOTTLES: Bottle[] = [...DEMO_ONLY, ...OWNER_SHELF_BOTTLES];

/** Starting settings. After seeding, the owners change these in admin. */
export const DEFAULT_SETTINGS: Settings = {
  atomizers: { 5: true, 10: true, 15: true },
  lowStockThreshold: 3,
  pickupDay: "Saturday",
  pickupPoints: [
    { id: "price-plaza", name: "Price Plaza, Chaguanas", time: "10:00am" },
    { id: "movietowne-pos", name: "MovieTowne, Port of Spain", time: "1:00pm" },
    { id: "east-gates", name: "East Gates Mall", time: "5:00pm" },
  ],
};

/**
 * Area → ODeliver zone. DRAFT: our best guess. Check it against ODeliver's own
 * area list; it's editable in the store (and in admin, M2).
 */
export const AREAS: Area[] = [
  // Urban
  { id: "port-of-spain", name: "Port of Spain", zone: "urban" },
  { id: "woodbrook", name: "Woodbrook", zone: "urban" },
  { id: "st-james", name: "St. James", zone: "urban" },
  { id: "belmont", name: "Belmont", zone: "urban" },
  { id: "diego-martin", name: "Diego Martin", zone: "urban" },
  { id: "maraval", name: "Maraval", zone: "urban" },
  { id: "san-juan", name: "San Juan", zone: "urban" },
  { id: "barataria", name: "Barataria", zone: "urban" },
  { id: "st-augustine", name: "St. Augustine", zone: "urban" },
  { id: "curepe", name: "Curepe", zone: "urban" },
  { id: "tunapuna", name: "Tunapuna", zone: "urban" },
  { id: "trincity", name: "Trincity", zone: "urban" },
  { id: "arima", name: "Arima", zone: "urban" },
  { id: "chaguanas", name: "Chaguanas", zone: "urban" },
  { id: "couva", name: "Couva", zone: "urban" },
  { id: "san-fernando", name: "San Fernando", zone: "urban" },
  { id: "marabella", name: "Marabella", zone: "urban" },
  // Rural
  { id: "chaguaramas", name: "Chaguaramas", zone: "rural" },
  { id: "arouca", name: "Arouca", zone: "rural" },
  { id: "sangre-grande", name: "Sangre Grande", zone: "rural" },
  { id: "princes-town", name: "Princes Town", zone: "rural" },
  { id: "penal", name: "Penal", zone: "rural" },
  { id: "siparia", name: "Siparia", zone: "rural" },
  { id: "gasparillo", name: "Gasparillo", zone: "rural" },
  { id: "rio-claro", name: "Rio Claro", zone: "rural" },
  // Extended
  { id: "point-fortin", name: "Point Fortin", zone: "extended" },
  { id: "la-brea", name: "La Brea", zone: "extended" },
  { id: "fyzabad", name: "Fyzabad", zone: "extended" },
  { id: "moruga", name: "Moruga", zone: "extended" },
  // Remote
  { id: "mayaro", name: "Mayaro", zone: "remote" },
  { id: "cedros", name: "Cedros", zone: "remote" },
  { id: "toco", name: "Toco", zone: "remote" },
  { id: "blanchisseuse", name: "Blanchisseuse", zone: "remote" },
  // Tobago
  { id: "tobago", name: "Tobago (any area)", zone: "tobago" },
];
