/**
 * Seed data for Smell Bess, generated by hand from `scent-lists.md`
 * (Bess List, locked 5 Oct 2026) and `CLAUDE.md`.
 *
 * - The 10 launch-buy scents are `live`. The rest of the Bess List is
 *   `coming_soon` until bought.
 * - Every rating, take, blurb, note list and "smells like" line here is our
 *   DRAFT (`draft: true`). The owner and girlfriend rewrite them in their own
 *   words before launch. Empty `smellsLike` means "owner to fill in".
 * - Prices are NOT here: they come from the tier (src/lib/pricing.ts).
 * - Bank details are NOT here: they live in .env.local only.
 */
import type { Area, Bottle, CuratedSet, Product, Settings } from "@/lib/types";

const none = { top: [], heart: [], base: [] };

export const PRODUCTS: Product[] = [
  // ---------------------------------------------------------- launch buy (10)
  {
    id: "liquid-brun",
    house: "French Avenue",
    name: "Liquid Brun",
    variant: "Original EDP",
    tier: "A",
    gender: "him",
    status: "live",
    smellsLike: ["Parfums de Marly Althaïr DNA"],
    notes: {
      top: ["cinnamon", "cardamom", "orange blossom"],
      heart: ["bourbon vanilla", "elemi"],
      base: ["praline", "musk", "guaiac wood"],
    },
    vibes: ["sweet", "gourmand", "spicy"],
    occasions: ["date", "lime"],
    ratings: { heat: 3, longevity: 4, projection: 4, compliments: 5 },
    take: { by: "him", text: "Warm vanilla and spice that gets noticed. Best after dark." },
    blurb: "Boozy vanilla with a cinnamon kick. A night-time compliment getter.",
    draft: true,
    hue: 28,
  },
  {
    id: "hawas-ice",
    house: "Rasasi",
    name: "Hawas Ice",
    tier: "A",
    gender: "him",
    status: "live",
    smellsLike: [],
    notes: {
      top: ["apple", "bergamot", "lemon"],
      heart: ["plum", "orange blossom"],
      base: ["musk", "ambergris"],
    },
    vibes: ["fresh", "aquatic", "fruity"],
    occasions: ["fete", "lime", "office"],
    ratings: { heat: 5, longevity: 4, projection: 4, compliments: 4 },
    take: { by: "him", text: "Cold, sweet and fresh. Made for a hot day in a crowd." },
    blurb: "An icy take on the Hawas DNA. A fete weapon.",
    draft: true,
    hue: 195,
  },
  {
    id: "hawas-diva",
    house: "Rasasi",
    name: "Hawas Diva",
    tier: "A",
    gender: "her",
    status: "live",
    smellsLike: [],
    notes: none,
    vibes: ["fruity", "floral", "sweet"],
    occasions: ["lime", "date", "fete"],
    ratings: { heat: 4, longevity: 4, projection: 4, compliments: 4 },
    take: { by: "her", text: "Fruity, girly and loud enough to be noticed." },
    blurb: "Bright fruity floral from the Hawas line.",
    draft: true,
    hue: 330,
  },
  {
    id: "angham",
    house: "Lattafa",
    name: "Angham",
    tier: "A",
    gender: "unisex",
    leans: "her",
    status: "live",
    smellsLike: [],
    notes: none,
    vibes: ["sweet", "floral"],
    occasions: ["date", "office"],
    ratings: { heat: 3, longevity: 4, projection: 3, compliments: 4 },
    take: { by: "her", text: "Soft and pretty. Leans feminine, but anyone can wear it." },
    blurb: "A smooth unisex scent that leans feminine.",
    draft: true,
    hue: 300,
  },
  {
    id: "khamrah",
    house: "Lattafa",
    name: "Khamrah",
    tier: "A",
    gender: "unisex",
    status: "live",
    smellsLike: ["Kilian Angels' Share DNA"],
    notes: {
      top: ["cinnamon", "nutmeg", "bergamot"],
      heart: ["dates", "praline", "tuberose"],
      base: ["vanilla", "tonka", "amberwood", "myrrh"],
    },
    vibes: ["sweet", "gourmand", "spicy", "amber"],
    occasions: ["date", "lime"],
    ratings: { heat: 3, longevity: 5, projection: 4, compliments: 5 },
    take: { by: "him", text: "The global best seller for a reason. Two sprays is plenty." },
    blurb: "Dates, cinnamon and vanilla. Rich, sweet and long-lasting.",
    draft: true,
    hue: 18,
  },
  {
    id: "khamrah-qahwa",
    house: "Lattafa",
    name: "Khamrah Qahwa",
    tier: "A",
    gender: "unisex",
    status: "live",
    smellsLike: [],
    notes: {
      top: ["cinnamon", "cardamom", "ginger"],
      heart: ["praline", "candied fruit", "white flowers"],
      base: ["coffee", "vanilla", "tonka", "benzoin"],
    },
    vibes: ["gourmand", "coffee", "spicy", "sweet"],
    occasions: ["date", "office"],
    ratings: { heat: 3, longevity: 5, projection: 4, compliments: 4 },
    take: { by: "him", text: "Khamrah with a coffee twist. A bit drier and easier for the office." },
    blurb: "Khamrah's sweet spice with roasted coffee on top.",
    draft: true,
    hue: 30,
  },
  {
    id: "yara",
    house: "Lattafa",
    name: "Yara",
    variant: "Original (pink)",
    tier: "A",
    gender: "her",
    status: "live",
    smellsLike: [],
    notes: {
      top: ["orchid", "heliotrope", "tangerine"],
      heart: ["gourmand accord", "tropical fruit"],
      base: ["vanilla", "musk", "sandalwood"],
    },
    vibes: ["sweet", "gourmand", "fruity"],
    occasions: ["lime", "date", "office"],
    ratings: { heat: 3, longevity: 4, projection: 3, compliments: 5 },
    take: { by: "her", text: "Creamy, sweet and soft. The one people ask about." },
    blurb: "Creamy pink gourmand. Sweet without being sickly.",
    draft: true,
    hue: 340,
  },
  {
    id: "rayhaan-aquatica",
    house: "Rayhaan",
    name: "Aquatica",
    tier: "A",
    gender: "him",
    leans: "him",
    status: "live",
    smellsLike: [],
    notes: none,
    vibes: ["fresh", "aquatic"],
    occasions: ["office", "lime", "fete"],
    ratings: { heat: 5, longevity: 3, projection: 3, compliments: 3 },
    take: { by: "him", text: "Clean and fresh. Spray it and go to work in the heat." },
    blurb: "Fresh aquatic that's built for TT heat. Men's, works unisex.",
    draft: true,
    hue: 185,
  },
  {
    id: "rayhaan-elixir",
    house: "Rayhaan",
    name: "Elixir",
    tier: "A",
    gender: "unisex",
    status: "live",
    smellsLike: [],
    notes: none,
    vibes: ["sweet", "amber"],
    occasions: ["date", "fete", "lime"],
    ratings: { heat: 4, longevity: 4, projection: 4, compliments: 4 },
    take: { by: "him", text: "Sold out everywhere else for a reason." },
    blurb: "A unisex crowd-pleaser that's hard to find locally.",
    draft: true,
    hue: 45,
  },
  {
    id: "supremacy-collectors-edition",
    house: "Afnan",
    name: "Supremacy Collector's Edition",
    tier: "A+",
    gender: "him",
    status: "live",
    smellsLike: [],
    notes: none,
    vibes: ["fruity", "woody", "fresh"],
    occasions: ["office", "date", "lime"],
    ratings: { heat: 4, longevity: 4, projection: 4, compliments: 4 },
    take: { by: "him", text: "The premium pick. Only Smell Bess carries it locally." },
    blurb: "Premium Arabian. Polished, confident and versatile.",
    draft: true,
    hue: 220,
  },

  // ---------------------------------------------------------- coming soon (13)
  comingSoon("rare-reef", "Afnan", "Rare Reef", "A", "unisex", ["fresh", "fruity"], 170),
  comingSoon("asad-bourbon", "Lattafa", "Asad Bourbon", "A", "him", ["spicy", "amber", "sweet"], 20),
  comingSoon("cdn-untold", "Armaf", "Club de Nuit Untold", "A", "unisex", ["sweet", "amber", "woody"], 350),
  comingSoon("marwa", "Arabiyat Prestige", "Marwa", "A", "him", ["fresh", "fruity"], 160),
  comingSoon("teriaq-intense", "Lattafa", "Teriaq Intense", "A", "unisex", ["sweet", "gourmand", "amber"], 10),
  comingSoon("nebras", "Lattafa", "Nebras", "A", "unisex", ["sweet", "gourmand"], 15),
  comingSoon("vintage-radio", "Lattafa", "Vintage Radio", "A", "unisex", ["woody", "sweet"], 40),
  comingSoon("amber-oud-gold", "Al Haramain", "Amber Oud Gold Edition", "A+", "unisex", ["sweet", "amber", "fruity"], 50),
  comingSoon("9pm-night-out", "Afnan", "9PM Night Out", "A+", "him", ["sweet", "spicy"], 265),
  comingSoon("yara-elixir", "Lattafa", "Yara Elixir", "A+", "her", ["sweet", "fruity"], 320),
  comingSoon("atheeri", "Lattafa", "Atheeri", "A+", "her", ["floral", "sweet"], 280),
  comingSoon("gos-full-house", "Jo Milano", "Game of Spades Full House", "N", "unisex", ["sweet", "woody"], 0),
  comingSoon("gos-wildcard", "Jo Milano", "Game of Spades Wildcard", "N", "unisex", ["floral", "woody"], 260),
];

function comingSoon(
  id: string,
  house: string,
  name: string,
  tier: Product["tier"],
  gender: Product["gender"],
  vibes: Product["vibes"],
  hue: number,
): Product {
  return {
    id,
    house,
    name,
    tier,
    gender,
    status: "coming_soon",
    smellsLike: [],
    notes: none,
    vibes,
    occasions: [],
    blurb: "Approved for the Bess List. On the way in a future drop.",
    draft: true,
    hue,
  };
}

/** Curated sets: DRAFT picks, Tier A launch scents only. */
export const SETS: CuratedSet[] = [
  {
    id: "fete-pack",
    name: "Fete Pack",
    description: "Three that survive heat, sweat and a crowd.",
    productIds: ["hawas-ice", "liquid-brun", "rayhaan-elixir"],
    draft: true,
  },
  {
    id: "office-safe",
    name: "Office Safe",
    description: "Fresh and polite. Nobody in the meeting will complain.",
    productIds: ["rayhaan-aquatica", "hawas-ice", "angham"],
    draft: true,
  },
  {
    id: "date-night",
    name: "Date Night",
    description: "Warm, sweet and close. For when you want them to lean in.",
    productIds: ["khamrah", "liquid-brun", "khamrah-qahwa"],
    draft: true,
  },
  {
    id: "her-gourmand",
    name: "Her Gourmand",
    description: "Sweet, creamy and fruity. Her side of the shelf.",
    productIds: ["yara", "hawas-diva", "angham"],
    draft: true,
  },
];

/**
 * DEMO stock so the shop can be clicked through locally. The launch bottles
 * haven't arrived yet (Jomashop order on or after 17 Oct 2026). Replace with
 * real bottle IDs and ml once they're in hand. Costs are landed TT$ from
 * scent-lists.md.
 */
export const DEMO_BOTTLES: Bottle[] = [
  { id: "LB-01", productId: "liquid-brun", sizeMl: 100, mlRemaining: 95, costTtd: 389, source: "Jomashop" },
  { id: "HI-01", productId: "hawas-ice", sizeMl: 100, mlRemaining: 22, costTtd: 389, source: "Jomashop" },
  { id: "HD-01", productId: "hawas-diva", sizeMl: 100, mlRemaining: 95, costTtd: 441, source: "Jomashop" },
  { id: "AN-01", productId: "angham", sizeMl: 100, mlRemaining: 95, costTtd: 420, source: "Jomashop" },
  { id: "KH-01", productId: "khamrah", sizeMl: 100, mlRemaining: 95, costTtd: 358, source: "Jomashop" },
  { id: "KQ-01", productId: "khamrah-qahwa", sizeMl: 100, mlRemaining: 60, costTtd: 373, source: "Jomashop" },
  { id: "YA-01", productId: "yara", sizeMl: 100, mlRemaining: 95, costTtd: 321, source: "Jomashop" },
  { id: "RA-01", productId: "rayhaan-aquatica", sizeMl: 100, mlRemaining: 95, costTtd: 300, source: "Local Rayhaan dealer" },
  { id: "RE-01", productId: "rayhaan-elixir", sizeMl: 100, mlRemaining: 12, costTtd: 300, source: "Local Rayhaan dealer" },
  { id: "SC-01", productId: "supremacy-collectors-edition", sizeMl: 100, mlRemaining: 95, costTtd: 650, source: "Jomashop" },
];

export const DEFAULT_SETTINGS: Settings = {
  atomizers: { 5: true, 10: true, 15: true },
  lowStockThreshold: 3,
};

/**
 * Area → ODeliver zone. DRAFT: our best guess. Check it against ODeliver's own
 * area list; it's editable in the store (and in admin, M2).
 */
export const AREAS: Area[] = [
  // Urban
  { id: "port-of-spain", name: "Port of Spain", zone: "urban" },
  { id: "woodbrook", name: "Woodbrook", zone: "urban" },
  { id: "st-james", name: "St. James", zone: "urban" },
  { id: "belmont", name: "Belmont", zone: "urban" },
  { id: "diego-martin", name: "Diego Martin", zone: "urban" },
  { id: "maraval", name: "Maraval", zone: "urban" },
  { id: "san-juan", name: "San Juan", zone: "urban" },
  { id: "barataria", name: "Barataria", zone: "urban" },
  { id: "st-augustine", name: "St. Augustine", zone: "urban" },
  { id: "curepe", name: "Curepe", zone: "urban" },
  { id: "tunapuna", name: "Tunapuna", zone: "urban" },
  { id: "trincity", name: "Trincity", zone: "urban" },
  { id: "arima", name: "Arima", zone: "urban" },
  { id: "chaguanas", name: "Chaguanas", zone: "urban" },
  { id: "couva", name: "Couva", zone: "urban" },
  { id: "san-fernando", name: "San Fernando", zone: "urban" },
  { id: "marabella", name: "Marabella", zone: "urban" },
  // Rural
  { id: "chaguaramas", name: "Chaguaramas", zone: "rural" },
  { id: "arouca", name: "Arouca", zone: "rural" },
  { id: "sangre-grande", name: "Sangre Grande", zone: "rural" },
  { id: "princes-town", name: "Princes Town", zone: "rural" },
  { id: "penal", name: "Penal", zone: "rural" },
  { id: "siparia", name: "Siparia", zone: "rural" },
  { id: "gasparillo", name: "Gasparillo", zone: "rural" },
  { id: "rio-claro", name: "Rio Claro", zone: "rural" },
  // Extended
  { id: "point-fortin", name: "Point Fortin", zone: "extended" },
  { id: "la-brea", name: "La Brea", zone: "extended" },
  { id: "fyzabad", name: "Fyzabad", zone: "extended" },
  { id: "moruga", name: "Moruga", zone: "extended" },
  // Remote
  { id: "mayaro", name: "Mayaro", zone: "remote" },
  { id: "cedros", name: "Cedros", zone: "remote" },
  { id: "toco", name: "Toco", zone: "remote" },
  { id: "blanchisseuse", name: "Blanchisseuse", zone: "remote" },
  // Tobago
  { id: "tobago", name: "Tobago (any area)", zone: "tobago" },
];
